apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
resources:
  - todo_app/manifests/namespace.yaml
  - todo_backend/manifests/postgres-secret.yaml
  - todo_backend/manifests/postgres-configmap.yaml
  - todo_backend/manifests/postgres-service.yaml
  - todo_backend/manifests/postgres-statefulset.yaml
  - todo_backend/manifests/deployment.yaml
  - todo_backend/manifests/service.yaml
  - todo_backend/manifests/cronjob.yaml
  - todo_app/volumes/persistentvolumeclaim.yaml
  - todo_app/manifests/deployment.yaml
  - todo_app/manifests/service.yaml
  - todo_app/manifests/ingress.yaml
images:
  - name: PROJECT/TODOAPP
    newName: kallepohjanjoki/todo_app
    newTag: v1.7
  - name: PROJECT/TODOBACKEND
    newName: kallepohjanjoki/todo_backend
    newTag: v1.2