apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todobackend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todobackend
  template:
    metadata:
      labels:
        app: todobackend
    spec:
      containers:
        - name: todobackend
          image: kallepohjanjoki/todo_backend:v1
          env:
            - name: PORT
              value: "8080"
