apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: pingpong-data
          persistentVolumeClaim:
            claimName: log-claim
      containers:
        - name: pingpong
          image: kallepohjanjoki/pingpong:v1.1
          env:
            - name: PORT
              value: "8080"
          volumeMounts:
            - name: pingpong-data
              mountPath: /shared/
