apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: todoapp-claim
      containers:
        - name: todoapp
          image: kallepohjanjoki/todo_app:v1.5
          env:
            - name: PORT
              value: "8000"
          volumeMounts:
            - name: image-cache
              mountPath: /images/
