apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todoapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: image-cache
          persistentVolumeClaim:
            claimName: todoapp-claim
      containers:
        - name: todoapp
          image: PROJECT/TODOAPP
          env:
            - name: PORT
              value: "8000"
            - name: IMAGE_PATH
              value: "/images/image.jpg"
            - name: IMAGE_SOURCE_URL
              value: "https://picsum.photos/1200"
            - name: TODO_BACKEND_URL
              value: "http://todobackend-svc:2345/todos"
          volumeMounts:
            - name: image-cache
              mountPath: /images/
